name: eclipse dash ip-check

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven

        #run: mvn -B org.eclipse.dash:license-tool-plugin:license-check -Dlicenses-check -Ddash.fail=true -Ddash.summary=DEPENDENCIES -P eclipse-licenses-check --file package-lock.json
        run: | 
              mvn dependency:get -Dartifact=org.eclipse.dash.licenses:0.0.1-SNAPSHOT -Ddest=.
              java -jar org.eclipse.dash.licenses.jar .package-lock.json
                
